from flask import Flask, jsonify
from flask_cors import CORS
import sqlite3

app = Flask(__name__)
CORS(app)  # Prevents Cross-Origin Request blocking

def get_telemetry():
    try:
        # Connect to the DB generated by your tracker
        conn = sqlite3.connect('mouse_data.db')
        cursor = conn.cursor()
        cursor.execute('SELECT distance, scroll FROM stats WHERE id = 1')
        row = cursor.fetchone()
        conn.close()
        
        if row:
            return {
                "status": "success",
                "distance_mm": round(row[0], 2),
                "scroll_mm": round(row[1], 2)
            }
        return {"status": "empty", "distance_mm": 0, "scroll_mm": 0}
    except Exception as e:
        return {"status": "error", "message": str(e)}

@app.route('/api/telemetry', methods=['GET'])
def telemetry():
    return jsonify(get_telemetry())

if __name__ == '__main__':
    # host='0.0.0.0' ensures the Cloudflare tunnel can route traffic to it
    app.run(host='0.0.0.0', port=5000, debug=True)